name: Build and deploy Vite React app to Azure Web App - JobFind

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # 3. Install dependencies
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./FRONTEND

      # 4. Build the frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./FRONTEND

      # 5. Zip only the dist folder
      - name: Zip build folder
        run: |
          rm -f app.zip        # remove old zip if exists
          zip -r app.zip ./*
        working-directory: ./FRONTEND/dist

      # 6. Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06F2BE1DB7B44529B436B3892976896B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E622A02AFAEE48F2AF32264D9B5F2E5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9E5A11EF25FD4FBFA317489A001FF0F4 }}

      # 7. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'JobFind'
          slot-name: 'Production'
          package: ./app.zip
